"""
THIS FILE IS AUTOMATICALLY GENERATED

Please make all edits in etc/generate_curried.py and re-run
cytoolz/tests/test_curried_toolzlike.py
"""

import cytoolz
from cytoolz import *
from .operator import *


get = cytoolz.curry(get)
tail = cytoolz.curry(tail)
pluck = cytoolz.curry(pluck)
update_in = cytoolz.curry(update_in)
get_in = cytoolz.curry(get_in)
iterate = cytoolz.curry(iterate)
partitionby = cytoolz.curry(partitionby)
unique = cytoolz.curry(unique)
valfilter = cytoolz.curry(valfilter)
merge_with = cytoolz.curry(merge_with)
take = cytoolz.curry(take)
nth = cytoolz.curry(nth)
take_nth = cytoolz.curry(take_nth)
interpose = cytoolz.curry(interpose)
accumulate = cytoolz.curry(accumulate)
map = cytoolz.curry(map)
partition = cytoolz.curry(partition)
valmap = cytoolz.curry(valmap)
memoize = cytoolz.curry(memoize)
mapcat = cytoolz.curry(mapcat)
reduceby = cytoolz.curry(reduceby)
countby = cytoolz.curry(countby)
sorted = cytoolz.curry(sorted)
drop = cytoolz.curry(drop)
remove = cytoolz.curry(remove)
merge = cytoolz.curry(merge)
itemfilter = cytoolz.curry(itemfilter)
sliding_window = cytoolz.curry(sliding_window)
reduce = cytoolz.curry(reduce)
keyfilter = cytoolz.curry(keyfilter)
do = cytoolz.curry(do)
topk = cytoolz.curry(topk)
partition_all = cytoolz.curry(partition_all)
assoc = cytoolz.curry(assoc)
join = cytoolz.curry(join)
filter = cytoolz.curry(filter)
itemmap = cytoolz.curry(itemmap)
interleave = cytoolz.curry(interleave)
cons = cytoolz.curry(cons)
groupby = cytoolz.curry(groupby)
keymap = cytoolz.curry(keymap)
dissoc = cytoolz.curry(dissoc)

from .exceptions import *
del cytoolz

