"""
THIS FILE IS AUTOMATICALLY GENERATED

Please make all edits in etc/generate_curried.py and re-run
cytoolz/tests/test_curried_toolzlike.py
"""
from __future__ import absolute_import

from operator import (
    iand,
    countOf,
    gt,
    __lshift__,
    __concat__,
    pow,
    imul,
    __iand__,
    ge,
    __irshift__,
    setslice,
    lshift,
    ipow,
    __lt__,
    sequenceIncludes,
    __inv__,
    __rshift__,
    le,
    __getslice__,
    __pos__,
    invert,
    contains,
    lt,
    __abs__,
    isSequenceType,
    add,
    delslice,
    _compare_digest,
    concat,
    irshift,
    __iconcat__,
    __ixor__,
    __doc__,
    __itruediv__,
    rshift,
    __getitem__,
    isub,
    __file__,
    pos,
    __irepeat__,
    __pow__,
    iconcat,
    __gt__,
    isCallable,
    __eq__,
    mod,
    __delitem__,
    __mod__,
    and_,
    __iadd__,
    isMappingType,
    setitem,
    __le__,
    truth,
    __floordiv__,
    __sub__,
    div,
    __ge__,
    ifloordiv,
    __ipow__,
    ixor,
    __isub__,
    inv,
    not_,
    __and__,
    __truediv__,
    repeat,
    __repeat__,
    __imod__,
    eq,
    iadd,
    index,
    __delslice__,
    xor,
    sub,
    __contains__,
    neg,
    getslice,
    ne,
    idiv,
    __package__,
    indexOf,
    attrgetter,
    abs,
    __invert__,
    methodcaller,
    truediv,
    mul,
    __neg__,
    __ne__,
    irepeat,
    is_,
    getitem,
    __ifloordiv__,
    __idiv__,
    isNumberType,
    ior,
    __setitem__,
    __or__,
    __add__,
    __name__,
    ilshift,
    __ilshift__,
    or_,
    __imul__,
    is_not,
    __not__,
    __setslice__,
    imod,
    itruediv,
    __xor__,
    __ior__,
    __div__,
    floordiv,
    __mul__,
    __index__,
    itemgetter,
    delitem,
)

import cytoolz

iand = cytoolz.curry(iand)
countOf = cytoolz.curry(countOf)
gt = cytoolz.curry(gt)
__lshift__ = cytoolz.curry(__lshift__)
__concat__ = cytoolz.curry(__concat__)
pow = cytoolz.curry(pow)
imul = cytoolz.curry(imul)
__iand__ = cytoolz.curry(__iand__)
ge = cytoolz.curry(ge)
__irshift__ = cytoolz.curry(__irshift__)
setslice = cytoolz.curry(setslice)
lshift = cytoolz.curry(lshift)
ipow = cytoolz.curry(ipow)
__lt__ = cytoolz.curry(__lt__)
sequenceIncludes = cytoolz.curry(sequenceIncludes)
__inv__ = cytoolz.curry(__inv__)
__rshift__ = cytoolz.curry(__rshift__)
le = cytoolz.curry(le)
__getslice__ = cytoolz.curry(__getslice__)
__pos__ = cytoolz.curry(__pos__)
contains = cytoolz.curry(contains)
lt = cytoolz.curry(lt)
__abs__ = cytoolz.curry(__abs__)
isSequenceType = cytoolz.curry(isSequenceType)
add = cytoolz.curry(add)
delslice = cytoolz.curry(delslice)
_compare_digest = cytoolz.curry(_compare_digest)
concat = cytoolz.curry(concat)
irshift = cytoolz.curry(irshift)
__iconcat__ = cytoolz.curry(__iconcat__)
__ixor__ = cytoolz.curry(__ixor__)
__itruediv__ = cytoolz.curry(__itruediv__)
rshift = cytoolz.curry(rshift)
__getitem__ = cytoolz.curry(__getitem__)
isub = cytoolz.curry(isub)
__irepeat__ = cytoolz.curry(__irepeat__)
__pow__ = cytoolz.curry(__pow__)
iconcat = cytoolz.curry(iconcat)
__gt__ = cytoolz.curry(__gt__)
isCallable = cytoolz.curry(isCallable)
__eq__ = cytoolz.curry(__eq__)
mod = cytoolz.curry(mod)
__delitem__ = cytoolz.curry(__delitem__)
__mod__ = cytoolz.curry(__mod__)
and_ = cytoolz.curry(and_)
__iadd__ = cytoolz.curry(__iadd__)
isMappingType = cytoolz.curry(isMappingType)
setitem = cytoolz.curry(setitem)
__le__ = cytoolz.curry(__le__)
__floordiv__ = cytoolz.curry(__floordiv__)
__sub__ = cytoolz.curry(__sub__)
div = cytoolz.curry(div)
__ge__ = cytoolz.curry(__ge__)
ifloordiv = cytoolz.curry(ifloordiv)
__ipow__ = cytoolz.curry(__ipow__)
ixor = cytoolz.curry(ixor)
__isub__ = cytoolz.curry(__isub__)
__and__ = cytoolz.curry(__and__)
__truediv__ = cytoolz.curry(__truediv__)
repeat = cytoolz.curry(repeat)
__repeat__ = cytoolz.curry(__repeat__)
__imod__ = cytoolz.curry(__imod__)
eq = cytoolz.curry(eq)
iadd = cytoolz.curry(iadd)
__delslice__ = cytoolz.curry(__delslice__)
xor = cytoolz.curry(xor)
sub = cytoolz.curry(sub)
__contains__ = cytoolz.curry(__contains__)
getslice = cytoolz.curry(getslice)
ne = cytoolz.curry(ne)
idiv = cytoolz.curry(idiv)
indexOf = cytoolz.curry(indexOf)
attrgetter = cytoolz.curry(attrgetter)
__invert__ = cytoolz.curry(__invert__)
methodcaller = cytoolz.curry(methodcaller)
truediv = cytoolz.curry(truediv)
mul = cytoolz.curry(mul)
__neg__ = cytoolz.curry(__neg__)
__ne__ = cytoolz.curry(__ne__)
irepeat = cytoolz.curry(irepeat)
is_ = cytoolz.curry(is_)
getitem = cytoolz.curry(getitem)
__ifloordiv__ = cytoolz.curry(__ifloordiv__)
__idiv__ = cytoolz.curry(__idiv__)
isNumberType = cytoolz.curry(isNumberType)
ior = cytoolz.curry(ior)
__setitem__ = cytoolz.curry(__setitem__)
__or__ = cytoolz.curry(__or__)
__add__ = cytoolz.curry(__add__)
ilshift = cytoolz.curry(ilshift)
__ilshift__ = cytoolz.curry(__ilshift__)
or_ = cytoolz.curry(or_)
__imul__ = cytoolz.curry(__imul__)
is_not = cytoolz.curry(is_not)
__not__ = cytoolz.curry(__not__)
__setslice__ = cytoolz.curry(__setslice__)
imod = cytoolz.curry(imod)
itruediv = cytoolz.curry(itruediv)
__xor__ = cytoolz.curry(__xor__)
__ior__ = cytoolz.curry(__ior__)
__div__ = cytoolz.curry(__div__)
floordiv = cytoolz.curry(floordiv)
__mul__ = cytoolz.curry(__mul__)
__index__ = cytoolz.curry(__index__)
itemgetter = cytoolz.curry(itemgetter)
delitem = cytoolz.curry(delitem)

del cytoolz

