"""
THIS FILE IS AUTOMATICALLY GENERATED

Please make all edits in etc/generate_curried.py and re-run
cytoolz/tests/test_curried_toolzlike.py
"""

from operator import (
    __eq__,
    pos,
    floordiv,
    __itruediv__,
    add,
    countOf,
    imul,
    concat,
    __ilshift__,
    __getitem__,
    abs,
    not_,
    __rshift__,
    indexOf,
    __irshift__,
    __builtins__,
    delitem,
    setitem,
    eq,
    __pow__,
    __ge__,
    __lt__,
    iadd,
    __index__,
    gt,
    iand,
    length_hint,
    and_,
    irshift,
    xor,
    getitem,
    truediv,
    imod,
    __lshift__,
    ge,
    __invert__,
    __ne__,
    index,
    __and__,
    __mul__,
    ior,
    __delitem__,
    __package__,
    __inv__,
    methodcaller,
    mul,
    __pos__,
    rshift,
    __iadd__,
    iconcat,
    inv,
    itruediv,
    __imod__,
    ilshift,
    contains,
    pow,
    sub,
    ipow,
    __floordiv__,
    __ior__,
    __cached__,
    __ipow__,
    __xor__,
    __truediv__,
    _abs,
    __name__,
    ifloordiv,
    attrgetter,
    __contains__,
    __file__,
    __abs__,
    __doc__,
    __loader__,
    __not__,
    __iconcat__,
    __ixor__,
    __setitem__,
    lshift,
    mod,
    le,
    invert,
    __neg__,
    isub,
    is_not,
    __ifloordiv__,
    or_,
    __concat__,
    __spec__,
    __le__,
    lt,
    __add__,
    __iand__,
    __sub__,
    __gt__,
    neg,
    __mod__,
    ne,
    __imul__,
    itemgetter,
    __or__,
    ixor,
    __isub__,
    is_,
    truth,
)

import cytoolz

__eq__ = cytoolz.curry(__eq__)
floordiv = cytoolz.curry(floordiv)
__itruediv__ = cytoolz.curry(__itruediv__)
add = cytoolz.curry(add)
countOf = cytoolz.curry(countOf)
imul = cytoolz.curry(imul)
concat = cytoolz.curry(concat)
__ilshift__ = cytoolz.curry(__ilshift__)
__getitem__ = cytoolz.curry(__getitem__)
__rshift__ = cytoolz.curry(__rshift__)
indexOf = cytoolz.curry(indexOf)
__irshift__ = cytoolz.curry(__irshift__)
delitem = cytoolz.curry(delitem)
setitem = cytoolz.curry(setitem)
eq = cytoolz.curry(eq)
__pow__ = cytoolz.curry(__pow__)
__ge__ = cytoolz.curry(__ge__)
__lt__ = cytoolz.curry(__lt__)
iadd = cytoolz.curry(iadd)
__index__ = cytoolz.curry(__index__)
gt = cytoolz.curry(gt)
iand = cytoolz.curry(iand)
length_hint = cytoolz.curry(length_hint)
and_ = cytoolz.curry(and_)
irshift = cytoolz.curry(irshift)
xor = cytoolz.curry(xor)
getitem = cytoolz.curry(getitem)
truediv = cytoolz.curry(truediv)
imod = cytoolz.curry(imod)
__lshift__ = cytoolz.curry(__lshift__)
ge = cytoolz.curry(ge)
__invert__ = cytoolz.curry(__invert__)
__ne__ = cytoolz.curry(__ne__)
__and__ = cytoolz.curry(__and__)
__mul__ = cytoolz.curry(__mul__)
ior = cytoolz.curry(ior)
__delitem__ = cytoolz.curry(__delitem__)
__inv__ = cytoolz.curry(__inv__)
methodcaller = cytoolz.curry(methodcaller)
mul = cytoolz.curry(mul)
__pos__ = cytoolz.curry(__pos__)
rshift = cytoolz.curry(rshift)
__iadd__ = cytoolz.curry(__iadd__)
iconcat = cytoolz.curry(iconcat)
itruediv = cytoolz.curry(itruediv)
__imod__ = cytoolz.curry(__imod__)
ilshift = cytoolz.curry(ilshift)
contains = cytoolz.curry(contains)
pow = cytoolz.curry(pow)
sub = cytoolz.curry(sub)
ipow = cytoolz.curry(ipow)
__floordiv__ = cytoolz.curry(__floordiv__)
__ior__ = cytoolz.curry(__ior__)
__ipow__ = cytoolz.curry(__ipow__)
__xor__ = cytoolz.curry(__xor__)
__truediv__ = cytoolz.curry(__truediv__)
_abs = cytoolz.curry(_abs)
ifloordiv = cytoolz.curry(ifloordiv)
attrgetter = cytoolz.curry(attrgetter)
__contains__ = cytoolz.curry(__contains__)
__abs__ = cytoolz.curry(__abs__)
__not__ = cytoolz.curry(__not__)
__iconcat__ = cytoolz.curry(__iconcat__)
__ixor__ = cytoolz.curry(__ixor__)
__setitem__ = cytoolz.curry(__setitem__)
lshift = cytoolz.curry(lshift)
mod = cytoolz.curry(mod)
le = cytoolz.curry(le)
__neg__ = cytoolz.curry(__neg__)
isub = cytoolz.curry(isub)
is_not = cytoolz.curry(is_not)
__ifloordiv__ = cytoolz.curry(__ifloordiv__)
or_ = cytoolz.curry(or_)
__concat__ = cytoolz.curry(__concat__)
__le__ = cytoolz.curry(__le__)
lt = cytoolz.curry(lt)
__add__ = cytoolz.curry(__add__)
__iand__ = cytoolz.curry(__iand__)
__sub__ = cytoolz.curry(__sub__)
__gt__ = cytoolz.curry(__gt__)
__mod__ = cytoolz.curry(__mod__)
ne = cytoolz.curry(ne)
__imul__ = cytoolz.curry(__imul__)
itemgetter = cytoolz.curry(itemgetter)
__or__ = cytoolz.curry(__or__)
ixor = cytoolz.curry(ixor)
__isub__ = cytoolz.curry(__isub__)
is_ = cytoolz.curry(is_)

del cytoolz

