package:
    name: cytoolz
    version: "0.7.3"

build:
    number: {{environ.get('BINSTAR_BUILD', 1)}}

requirements:
    build:
      - setuptools
      - python
      - cython
      - toolz
      - libpython # [win and not (win64 and py34)]

    run:
      - python
      - libpython # [win and not (win64 and py34)]

test:
    requires:
      - pytest
      - nose
      - toolz
    imports:
      - cytoolz
    commands:
      - py.test -x --doctest-modules --pyargs cytoolz

about:
    home: http://toolz.readthedocs.org/
    license: BSD
